//NUMBER CARDS ARRAY
const skaiciai = [
  {
    id: 0,
    img: require("../media/images/card_images/n0.jpg"),
    name: "Nulis",
    sound: require("../assets/n0.mp3"),
  },
  {
    id: 1,
    img: require("../media/images/card_images/n1.jpg"),
    name: "Vienas",
    sound: require("../assets/n1.mp3"),
  },
  {
    id: 2,
    img: require("../media/images/card_images/n2.jpg"),
    name: "Du",
    sound: require("../assets/n2.mp3"),
  },
  {
    id: 3,
    img: require("../media/images/card_images/n3.jpg"),
    name: "Trys",
    sound: require("../assets/n3.mp3"),
  },
  {
    id: 4,
    img: require("../media/images/card_images/n4.jpg"),
    name: "Keturi",
    sound: require("../assets/n4.mp3"),
  },
  {
    id: 5,
    img: require("../media/images/card_images/n5.jpg"),
    name: "Penki",
    sound: require("../assets/n5.mp3"),
  },
  {
    id: 6,
    img: require("../media/images/card_images/n6.jpg"),
    name: "Šeši",
    sound: require("../assets/n6.mp3"),
  },
  {
    id: 7,
    img: require("../media/images/card_images/n7.jpg"),
    name: "Septyni",
    sound: require("../assets/n7.mp3"),
  },
  {
    id: 8,
    img: require("../media/images/card_images/n8.jpg"),
    name: "Aštuoni",
    sound: require("../assets/n8.mp3"),
  },
  {
    id: 9,
    img: require("../media/images/card_images/n9.jpg"),
    name: "Devyni",
    sound: require("../assets/n9.mp3"),
  },
  {
    id: 10,
    img: require("../media/images/card_images/n10.jpg"),
    name: "Dešimt",
    sound: require("../assets/n10.mp3"),
  },
  {
    id: 11,
    img: require("../media/images/card_images/n11.jpg"),
    name: "Venuolika",
    sound: require("../assets/n11.mp3"),
  },
  {
    id: 12,
    img: require("../media/images/card_images/n12.jpg"),
    name: "Dvylika",
    sound: require("../assets/n12.mp3"),
  },
  {
    id: 13,
    img: require("../media/images/card_images/n13.jpg"),
    name: "Trylika",
    sound: require("../assets/n13.mp3"),
  },
  {
    id: 14,
    img: require("../media/images/card_images/n14.jpg"),
    name: "Keturiolika",
    sound: require("../assets/n14.mp3"),
  },
  {
    id: 15,
    img: require("../media/images/card_images/n15.jpg"),
    name: "Penkiolika",
    sound: require("../assets/n15.mp3"),
  },
  {
    id: 16,
    img: require("../media/images/card_images/n16.jpg"),
    name: "Šešiolika",
    sound: require("../assets/n16.mp3"),
  },
  {
    id: 17,
    img: require("../media/images/card_images/n17.jpg"),
    name: "Septyniolika",
    sound: require("../assets/n17.mp3"),
  },
  {
    id: 18,
    img: require("../media/images/card_images/n18.jpg"),
    name: "Aštuoniolika",
    sound: require("../assets/n18.mp3"),
  },
  {
    id: 19,
    img: require("../media/images/card_images/n19.jpg"),
    name: "Deviniolika",
    sound: require("../assets/n19.mp3"),
  },
  {
    id: 20,
    img: require("../media/images/card_images/n20.jpg"),
    name: "Dvidešimt",
    sound: require("../assets/n20.mp3"),
  },
  {
    id: 21,
    img: require("../media/images/card_images/n21.jpg"),
    name: "Dvidešimt vienas",
    sound: require("../assets/n21.mp3"),
  },
  {
    id: 22,
    img: require("../media/images/card_images/n22.jpg"),
    name: "Dvidešimt du",
    sound: require("../assets/n22.mp3"),
  },
  {
    id: 23,
    img: require("../media/images/card_images/n23.jpg"),
    name: "Dvidešimt trys",
    sound: require("../assets/n23.mp3"),
  },
  {
    id: 24,
    img: require("../media/images/card_images/n24.jpg"),
    name: "Dvidešimt keturi",
    sound: require("../assets/n24.mp3"),
  },
  {
    id: 25,
    img: require("../media/images/card_images/n25.jpg"),
    name: "Dvidešimt penki",
    sound: require("../assets/n25.mp3"),
  },
  {
    id: 26,
    img: require("../media/images/card_images/n26.jpg"),
    name: "Dvidešimt šeši",
    sound: require("../assets/n26.mp3"),
  },
  {
    id: 27,
    img: require("../media/images/card_images/n27.jpg"),
    name: "Dvidešimt septyni",
    sound: require("../assets/n27.mp3"),
  },
  {
    id: 28,
    img: require("../media/images/card_images/n28.jpg"),
    name: "Dvidešimt aštuoni",
    sound: require("../assets/n28.mp3"),
  },
  {
    id: 29,
    img: require("../media/images/card_images/n29.jpg"),
    name: "Dvidešimt devyni",
    sound: require("../assets/n29.mp3"),
  },
  {
    id: 30,
    img: require("../media/images/card_images/n30.jpg"),
    name: "Trisdešimt",
    sound: require("../assets/n30.mp3"),
  },
];
//CLOATHING
const rubai = [
  {
    id: 0,
    img: require("../media/images/card_images/aukstakulniai.jpg"),
    name: "Aukštakulniai",
    sound: require("../assets/aukstakulniai.mp3"),
  },
  {
    id: 1,
    img: require("../media/images/card_images/beisbolo_kepuraite.jpg"),
    name: "Beisbolo kepuraitė",
    sound: require("../assets/beisbolo_kepuraite.mp3"),
  },
  {
    id: 2,
    img: require("../media/images/card_images/botai.jpg"),
    name: "Botai",
    sound: require("../assets/botai.mp3"),
  },
  {
    id: 3,
    img: require("../media/images/card_images/dirzas.jpg"),
    name: "Diržas",
    sound: require("../assets/dirzas.mp3"),
  },
  {
    id: 4,
    img: require("../media/images/card_images/kaklaraistis.jpg"),
    name: "Kaklaraištis",
    sound: require("../assets/kaklaraistis.mp3"),
  },
  {
    id: 5,
    img: require("../media/images/card_images/kaspinas.jpg"),
    name: "Kaspinas",
    sound: require("../assets/kaspinas.mp3"),
  },
  {
    id: 6,
    img: require("../media/images/card_images/kepure.jpg"),
    name: "Kepurė",
    sound: require("../assets/kepure.mp3"),
  },
  {
    id: 7,
    img: require("../media/images/card_images/kojines.jpg"),
    name: "Kojinės",
    sound: require("../assets/kojines.mp3"),
  },
  {
    id: 8,
    img: require("../media/images/card_images/kostiumas.jpg"),
    name: "Kostiumas",
    sound: require("../assets/kostiumas.mp3"),
  },
  {
    id: 9,
    img: require("../media/images/card_images/kuprine.jpg"),
    name: "Kuprinė",
    sound: require("../assets/kuprine.mp3"),
  },
  {
    id: 10,
    img: require("../media/images/card_images/laikrodis.jpg"),
    name: "Laikrodis",
    sound: require("../assets/laikrodis.mp3"),
  },
  {
    id: 11,
    img: require("../media/images/card_images/lietpaltis.jpg"),
    name: "Lietpaltis",
    sound: require("../assets/lietpaltis.mp3"),
  },
  {
    id: 12,
    img: require("../media/images/card_images/marskineliai.jpg"),
    name: "Marškinėliai",
    sound: require("../assets/marskineliai.mp3"),
  },
  {
    id: 13,
    img: require("../media/images/card_images/marskiniai.jpg"),
    name: "Marškiniai",
    sound: require("../assets/marskiniai.mp3"),
  },
  {
    id: 14,
    img: require("../media/images/card_images/megstinis.jpg"),
    name: "Megztinis",
    sound: require("../assets/megstinis.mp3"),
  },
  {
    id: 15,
    img: require("../media/images/card_images/paltas.jpg"),
    name: "Paltas",
    sound: require("../assets/paltas.mp3"),
  },
  {
    id: 16,
    img: require("../media/images/card_images/pirstines.jpg"),
    name: "Pitštinės",
    sound: require("../assets/pirstines.mp3"),
  },
  {
    id: 17,
    img: require("../media/images/card_images/salikas.jpg"),
    name: "Šalikas",
    sound: require("../assets/salikas.mp3"),
  },
  {
    id: 18,
    img: require("../media/images/card_images/skrybele.jpg"),
    name: "Skrybelė",
    sound: require("../assets/skrybele.mp3"),
  },
  {
    id: 19,
    img: require("../media/images/card_images/slepetes.jpg"),
    name: "Šlepetės",
    sound: require("../assets/slepetes.mp3"),
  },
  {
    id: 16,
    img: require("../media/images/card_images/striuke.jpg"),
    name: "Striukė",
    sound: require("../assets/striuke.mp3"),
  },
  {
    id: 17,
    img: require("../media/images/card_images/suknele.jpg"),
    name: "Suknelė",
    sound: require("../assets/suknele.mp3"),
  },
  {
    id: 18,
    img: require("../media/images/card_images/trumpikes.jpg"),
    name: "Trumpikes",
    sound: require("../assets/trumpikes.mp3"),
  },
];
//FRUITS
const vaisiai = [
  {
    id: 0,
    img: require("../media/images/card_images/braske.jpg"),
    name: "Braškė",
    sound: require("../assets/braske.mp3"),
  },
  {
    id: 1,
    img: require("../media/images/card_images/agurkas.jpg"),
    name: "Agurkas",
    sound: require("../assets/agurkas.mp3"),
  },
  {
    id: 2,
    img: require("../media/images/card_images/obuolys.jpg"),
    name: "Obuolys",
    sound: require("../assets/obuolys.mp3"),
  },
  {
    id: 3,
    img: require("../media/images/card_images/melyne.jpg"),
    name: "Mėlynė",
    sound: require("../assets/melyne.mp3"),
  },
  {
    id: 4,
    img: require("../media/images/card_images/pomidoras.jpg"),
    name: "Pomidoras",
    sound: require("../assets/pomidoras.mp3"),
  },
  {
    id: 5,
    img: require("../media/images/card_images/vysnia.jpg"),
    name: "Vyšnia",
    sound: require("../assets/vysnia.mp3"),
  },
  {
    id: 6,
    img: require("../media/images/card_images/bananas.jpg"),
    name: "Bananas",
    sound: require("../assets/bananas.mp3"),
  },
  {
    id: 7,
    img: require("../media/images/card_images/citrina.jpg"),
    name: "Citrina",
    sound: require("../assets/citrina.mp3"),
  },
  {
    id: 8,
    img: require("../media/images/card_images/kriause.jpg"),
    name: "Kriaušė",
    sound: require("../assets/kriause.mp3"),
  },
  {
    id: 9,
    img: require("../media/images/card_images/apelsinas.jpg"),
    name: "Apelsinas",
    sound: require("../assets/apelsinas.mp3"),
  },
  {
    id: 10,
    img: require("../media/images/card_images/arbuzas.jpg"),
    name: "Arbūzas",
    sound: require("../assets/arbuzas.mp3"),
  },
  {
    id: 11,
    img: require("../media/images/card_images/morka.jpg"),
    name: "Morka",
    sound: require("../assets/morka.mp3"),
  },
  {
    id: 12,
    img: require("../media/images/card_images/brokolis.jpg"),
    name: "Brokolis",
    sound: require("../assets/brokolis.mp3"),
  },
  {
    id: 13,
    img: require("../media/images/card_images/vynuoge.jpg"),
    name: "Vynuogė",
    sound: require("../assets/vynuoge.mp3"),
  },
  {
    id: 14,
    img: require("../media/images/card_images/ananasas.jpg"),
    name: "Ananasas",
    sound: require("../assets/ananasas.mp3"),
  },
  {
    id: 15,
    img: require("../media/images/card_images/bulve.jpg"),
    name: "Bulvė",
    sound: require("../assets/bulve.mp3"),
  },
  {
    id: 16,
    img: require("../media/images/card_images/kopustas.jpg"),
    name: "Kopūstas",
    sound: require("../assets/kopustas.mp3"),
  },
  {
    id: 17,
    img: require("../media/images/card_images/cesnakas.jpg"),
    name: "Česnakas",
    sound: require("../assets/cesnakas.mp3"),
  },
  {
    id: 18,
    img: require("../media/images/card_images/zirnis.jpg"),
    name: "Žirnis",
    sound: require("../assets/zirnis.mp3"),
  },
  {
    id: 19,
    img: require("../media/images/card_images/svogunas.jpg"),
    name: "Svogūnas",
    sound: require("../assets/svogunas.mp3"),
  },
];
//SHAPES
const formos = [
  {
    id: 0,
    img: require("../media/images/card_images/geltonas_apskritimas.jpg"),
    name: "Geltonas apskritimas",
    sound: require("../assets/geltonas_apskrytimas.mp3"),
  },
  {
    id: 1,
    img: require("../media/images/card_images/geltonas_keturkampis.jpg"),
    name: "Geltonas keturkampis",
    sound: require("../assets/geltonas_keturkampis.mp3"),
  },
  {
    id: 2,
    img: require("../media/images/card_images/geltonas_kvadratas.jpg"),
    name: "Geltonas kvadratas",
    sound: require("../assets/geltonas_kvadratas.mp3"),
  },
  {
    id: 3,
    img: require("../media/images/card_images/melynas_keturkampis.jpg"),
    name: "Mėlynas keturkampis",
    sound: require("../assets/melynas_keturkampis.mp3"),
  },
  {
    id: 4,
    img: require("../media/images/card_images/melynas_rombas.jpg"),
    name: "Mėlynas rombas",
    sound: require("../assets/melynas_rombas.mp3"),
  },
  {
    id: 5,
    img: require("../media/images/card_images/melynas_trikampis.jpg"),
    name: "Mėlynas trikampis",
    sound: require("../assets/melynas_trikampis.mp3"),
  },
  {
    id: 6,
    img: require("../media/images/card_images/orandzinis_keturkampis.jpg"),
    name: "Orandžinis keturkampis",
    sound: require("../assets/orandzinis_keturkampis.mp3"),
  },
  {
    id: 7,
    img: require("../media/images/card_images/orandzinis_kvadratas.jpg"),
    name: "Orandžinis kvadratas",
    sound: require("../assets/orandzinis_kvadratas.mp3"),
  },
  {
    id: 8,
    img: require("../media/images/card_images/orandzinis_rombas.jpg"),
    name: "Orandžinis rombas",
    sound: require("../assets/orandzinis_rombas.mp3"),
  },
  {
    id: 9,
    img: require("../media/images/card_images/pilkas_apskritimas.jpg"),
    name: "Pilkas apskritimas",
    sound: require("../assets/pilkas_apskritimas.mp3"),
  },
  {
    id: 10,
    img: require("../media/images/card_images/pilkas_ovalas.jpg"),
    name: "Pilkas ovalas",
    sound: require("../assets/pilkas_ovalas.mp3"),
  },
  {
    id: 11,
    img: require("../media/images/card_images/pilkas_sesiakampis.jpg"),
    name: "Pilkas šešiakampis",
    sound: require("../assets/pilkas_sesiakampis.mp3"),
  },
  {
    id: 12,
    img: require("../media/images/card_images/raudonas_apskritimas.jpg"),
    name: "Raudonas apskritimas",
    sound: require("../assets/raudonas_apskritimas.mp3"),
  },
  {
    id: 13,
    img: require("../media/images/card_images/raudonas_kvadratas.jpg"),
    name: "Raudonas kvadratas",
    sound: require("../assets/raudonas_kvadratas.mp3"),
  },
  {
    id: 14,
    img: require("../media/images/card_images/raudonas_ovalas.jpg"),
    name: "Raudonas ovalas",
    sound: require("../assets/raudonas_ovalas.mp3"),
  },
  {
    id: 15,
    img: require("../media/images/card_images/rozine_sirdis.jpg"),
    name: "Rožinė širdis",
    sound: require("../assets/rozine_sirdis.mp3"),
  },
  {
    id: 16,
    img: require("../media/images/card_images/rozine_zvaigzde.jpg"),
    name: "Rožinė žvaigždė",
    sound: require("../assets/rozine_zvaigzde.mp3"),
  },
  {
    id: 17,
    img: require("../media/images/card_images/rozinis_trikampis.jpg"),
    name: "Rožinis trikampis",
    sound: require("../assets/rozinis_trikampis.mp3"),
  },
  {
    id: 18,
    img: require("../media/images/card_images/ruda_zvaigzde.jpg"),
    name: "Ruda žvaigždė",
    sound: require("../assets/ruda_zvaigzde.mp3"),
  },
  {
    id: 19,
    img: require("../media/images/card_images/rudas_ovalas.jpg"),
    name: "Rudas ovalas",
    sound: require("../assets/rudas_ovalas.mp3"),
  },
  {
    id: 20,
    img: require("../media/images/card_images/rudas_sesiakampis.jpg"),
    name: "Rudas šešiakampis",
    sound: require("../assets/rudas_sesiakampis.mp3"),
  },
  {
    id: 21,
    img: require("../media/images/card_images/violetine_sirdis.jpg"),
    name: "Violetinė širdis",
    sound: require("../assets/violetine_sirdis.mp3"),
  },
  {
    id: 22,
    img: require("../media/images/card_images/violetine_zvaigzde.jpg"),
    name: "Viletinė žvaigždė",
    sound: require("../assets/violetine_zvaigzde.mp3"),
  },
  {
    id: 23,
    img: require("../media/images/card_images/violetinis_sesiakampis.jpg"),
    name: "Violetinis šešiakampis",
    sound: require("../assets/violetinis_sesiakampis.mp3"),
  },
  {
    id: 24,
    img: require("../media/images/card_images/zalia_sirdis.jpg"),
    name: "Žalia širdis",
    sound: require("../assets/zalia_sirdis.mp3"),
  },
  {
    id: 25,
    img: require("../media/images/card_images/zalias_rombas.jpg"),
    name: "Žalias rombas",
    sound: require("../assets/zalias_rombas.mp3"),
  },
  {
    id: 26,
    img: require("../media/images/card_images/zalias_trikampis.jpg"),
    name: "Žalias trikampis",
    sound: require("../assets/zalias_trikampis.mp3"),
  },
];
//ANIMALS
const gyvunai = [
  {
    id: 0,
    img: require("../media/images/card_images/ozka.jpg"),
    name: "Ožka",
    sound: require("../assets/ozka.mp3"),
  },
  {
    id: 1,
    img: require("../media/images/card_images/briedis.jpg"),
    name: "Briedis",
    sound: require("../assets/briedis.mp3"),
  },
  {
    id: 2,
    img: require("../media/images/card_images/raganosis.jpg"),
    name: "Raganosis",
    sound: require("../assets/raganosis.mp3"),
  },
  {
    id: 3,
    img: require("../media/images/card_images/arklys.jpg"),
    name: "Arklys",
    sound: require("../assets/arklys.mp3"),
  },
  {
    id: 4,
    img: require("../media/images/card_images/muse.jpg"),
    name: "Musė",
    sound: require("../assets/muse.mp3"),
  },
  {
    id: 5,
    img: require("../media/images/card_images/strutis.jpg"),
    name: "Strutis",
    sound: require("../assets/strutis.mp3"),
  },
  {
    id: 6,
    img: require("../media/images/card_images/krokodilas.jpg"),
    name: "Krokodilas",
    sound: require("../assets/krokodilas.mp3"),
  },
  {
    id: 7,
    img: require("../media/images/card_images/vilkas.jpg"),
    name: "Vilkas",
    sound: require("../assets/vilkas.mp3"),
  },
  {
    id: 8,
    img: require("../media/images/card_images/karve.jpg"),
    name: "Karvė",
    sound: require("../assets/karve.mp3"),
  },
  {
    id: 9,
    img: require("../media/images/card_images/voras.jpg"),
    name: "Voras",
    sound: require("../assets/voras.mp3"),
  },
  {
    id: 10,
    img: require("../media/images/card_images/dramblys.jpg"),
    name: "Dramblys",
    sound: require("../assets/dramblys.mp3"),
  },
  {
    id: 11,
    img: require("../media/images/card_images/antis.jpg"),
    name: "Antis",
    sound: require("../assets/antis.mp3"),
  },
  {
    id: 12,
    img: require("../media/images/card_images/varle.jpg"),
    name: "Varlė",
    sound: require("../assets/varle.mp3"),
  },
  {
    id: 13,
    img: require("../media/images/card_images/drugelis.jpg"),
    name: "Drugelis",
    sound: require("../assets/drugelis.mp3"),
  },
  {
    id: 14,
    img: require("../media/images/card_images/vezlys.jpg"),
    name: "Vėžlys",
    sound: require("../assets/vezlys.mp3"),
  },
  {
    id: 15,
    img: require("../media/images/card_images/liutas.jpg"),
    name: "Liūtas",
    sound: require("../assets/liutas.mp3"),
  },
  {
    id: 16,
    img: require("../media/images/card_images/avis.jpg"),
    name: "Avis",
    sound: require("../assets/avis.mp3"),
  },
  {
    id: 17,
    img: require("../media/images/card_images/zasis.jpg"),
    name: "Žąsis",
    sound: require("../assets/zasis.mp3"),
  },
  {
    id: 18,
    img: require("../media/images/card_images/pingvinas.jpg"),
    name: "Pingvinas",
    sound: require("../assets/pingvinas.mp3"),
  },
  {
    id: 19,
    img: require("../media/images/card_images/meska.jpg"),
    name: "Meška",
    sound: require("../assets/meska.mp3"),
  },
  {
    id: 20,
    img: require("../media/images/card_images/lape.jpg"),
    name: "Lapė",
    sound: require("../assets/lape.mp3"),
  },
  {
    id: 21,
    img: require("../media/images/card_images/kate.jpg"),
    name: "Katė",
    sound: require("../assets/kate.mp3"),
  },
  {
    id: 22,
    img: require("../media/images/card_images/suo.jpg"),
    name: "Šuo",
    sound: require("../assets/suo.mp3"),
  },
  {
    id: 23,
    img: require("../media/images/card_images/zebras.jpg"),
    name: "Zebras",
    sound: require("../assets/zebras.mp3"),
  },
  {
    id: 24,
    img: require("../media/images/card_images/gulbe.jpg"),
    name: "Gulbė",
    sound: require("../assets/gulbe.mp3"),
  },
  {
    id: 25,
    img: require("../media/images/card_images/pele.jpg"),
    name: "Pelė",
    sound: require("../assets/pele.mp3"),
  },
  {
    id: 26,
    img: require("../media/images/card_images/gandras.jpg"),
    name: "Gandras",
    sound: require("../assets/gandras.mp3"),
  },
  {
    id: 27,
    img: require("../media/images/card_images/ruonis.jpg"),
    name: "Ruonis",
    sound: require("../assets/ruonis.mp3"),
  },
  {
    id: 28,
    img: require("../media/images/card_images/zuikis.jpg"),
    name: "Zuikis",
    sound: require("../assets/zuikis.mp3"),
  },
  {
    id: 29,
    img: require("../media/images/card_images/kiaule.jpg"),
    name: "Kiaulė",
    sound: require("../assets/kiaule.mp3"),
  },
];

const transportas = [
  {
    id: 0,
    img: require("../media/images/card_images/valtis.jpg"),
    name: "Valtis",
    sound: require("../assets/valtis.mp3"),
  },
  {
    id: 0,
    img: require("../media/images/card_images/keleivinis_lektuvas.jpg"),
    name: "Keleivinis lėktuvas",
    sound: require("../assets/keleivinis_lektuvas.mp3"),
  },
  {
    id: 0,
    img: require("../media/images/card_images/buldozeris.jpg"),
    name: "Buldozeris",
    sound: require("../assets/buldozeris.mp3"),
  },
  {
    id: 0,
    img: require("../media/images/card_images/sraiktasparnis.jpg"),
    name: "Sraigtasparnis",
    sound: require("../assets/sraiktasparnis.mp3"),
  },
  {
    id: 0,
    img: require("../media/images/card_images/raketa.jpg"),
    name: "Raketa",
    sound: require("../assets/raketa.mp3"),
  },
  {
    id: 0,
    img: require("../media/images/card_images/dviratis.jpg"),
    name: "Dviratis",
    sound: require("../assets/dviratis.mp3"),
  },
  {
    id: 0,
    img: require("../media/images/card_images/rieduciai.jpg"),
    name: "Riedučiai",
    sound: require("../assets/rieduciai.mp3"),
  },
  {
    id: 0,
    img: require("../media/images/card_images/oro_balionas.jpg"),
    name: "Oro balionas",
    sound: require("../assets/oro_balionas.mp3"),
  },
  {
    id: 0,
    img: require("../media/images/card_images/riedlente.jpg"),
    name: "Riedlentė",
    sound: require("../assets/riedlente.mp3"),
  },
  {
    id: 0,
    img: require("../media/images/card_images/garlaivis.jpg"),
    name: "Garlaivis",
    sound: require("../assets/garlaivis.mp3"),
  },
  {
    id: 0,
    img: require("../media/images/card_images/karieta.jpg"),
    name: "Karieta",
    sound: require("../assets/karieta.mp3"),
  },
  {
    id: 0,
    img: require("../media/images/card_images/garvezys.jpg"),
    name: "Garvežys",
    sound: require("../assets/garvezys.mp3"),
  },
  {
    id: 0,
    img: require("../media/images/card_images/paspirtukas.jpg"),
    name: "Paspirtukas",
    sound: require("../assets/paspirtukas.mp3"),
  },
  {
    id: 0,
    img: require("../media/images/card_images/traukinys.jpg"),
    name: "Traukinys",
    sound: require("../assets/traukinys.mp3"),
  },
  {
    id: 0,
    img: require("../media/images/card_images/troleibusas.jpg"),
    name: "Troleibusas",
    sound: require("../assets/troleibusas.mp3"),
  },
  {
    id: 0,
    img: require("../media/images/card_images/lengvasis_automobilis.jpg"),
    name: "Lengvasis automobilis",
    sound: require("../assets/lengvasis_automobilis.mp3"),
  },
  {
    id: 0,
    img: require("../media/images/card_images/sunkvezimis.jpg"),
    name: "Sunkvežimis",
    sound: require("../assets/sunkvezimis.mp3"),
  },
  {
    id: 0,
    img: require("../media/images/card_images/kombainas.jpg"),
    name: "Kombainas",
    sound: require("../assets/kombainas.mp3"),
  },
  {
    id: 0,
    img: require("../media/images/card_images/triratukas.jpg"),
    name: "Triratukas",
    sound: require("../assets/triratukas.mp3"),
  },
  {
    id: 0,
    img: require("../media/images/card_images/traktorius.jpg"),
    name: "Traktorius",
    sound: require("../assets/traktorius.mp3"),
  },
  {
    id: 0,
    img: require("../media/images/card_images/kruizinis_laivas.jpg"),
    name: "Kruizinis laivas",
    sound: require("../assets/kruizinis_laivas.mp3"),
  },
  {
    id: 0,
    img: require("../media/images/card_images/motociklas.jpg"),
    name: "Motociklas",
    sound: require("../assets/motociklas.mp3"),
  },
  {
    id: 0,
    img: require("../media/images/card_images/autobusas.jpg"),
    name: "Autobusas",
    sound: require("../assets/autobusas.mp3"),
  },
  {
    id: 0,
    img: require("../media/images/card_images/motoroleris.jpg"),
    name: "Motoroleris",
    sound: require("../assets/motoroleris.mp3"),
  },
  {
    id: 0,
    img: require("../media/images/card_images/dirizablis.jpg"),
    name: "Dirižablis",
    sound: require("../assets/dirizablis.mp3"),
  },
  {
    id: 0,
    img: require("../media/images/card_images/visureigis.jpg"),
    name: "Visureigis",
    sound: require("../assets/visureigis.mp3"),
  },
  {
    id: 0,
    img: require("../media/images/card_images/naikintuvas.jpg"),
    name: "Naikintuvas",
    sound: require("../assets/naikintuvas.mp3"),
  },
];

const patarles = [
  "Laikas išmokti ką nors naujo?",
  "Ka išmoksi ant pečių nenešiosi",
  "Mokslas žmogų puošia",
  "Mokslas – didelė galybė",
  "Mokslo šaknys karčios, bet vaisiai saldūs",
  "Žmogus be mokslo - kaip namai be langų",
  "Viskas sunku, kol nepalieka lengva",
  "Niekas negimė mokytas",
];

export const kategorijos = [
  {
    id: 0,
    name: "Skaičiai",
    cards: skaiciai,
    img: require("../media/images/t_skaiciai.jpg"),
  },
  {
    id: 1,
    name: "Rūbai",
    cards: rubai,
    img: require("../media/images/t_rubai.jpg"),
  },
  {
    id: 2,
    name: "Vaisiai ir daržovės",
    cards: vaisiai,
    img: require("../media/images/t_skaiciai.jpg"),
  },
  {
    id: 3,
    name: "Spalvos ir formos",
    cards: formos,
    img: require("../media/images/t_skaiciai.jpg"),
  },
  {
    id: 4,
    name: "Gyvūnai",
    cards: gyvunai,
    img: require("../media/images/t_skaiciai.jpg"),
  },
  {
    id: 5,
    name: "Transportas",
    cards: transportas,
    img: require("../media/images/t_transportas.jpg"),
  },
];
